window_mode:                      "fixed"
output_format:                    "json"
debug_mode:                       True
send_thread_data:                 True
net_monitor:                      True
nat_trace:                        True
print_net_details:                True
dynamic_tcp_client_port_masking:  True
power_measure:                    True
memory_measure:                   True
disk_measure:                     True
file_measure:                     True
